### ISSUE TITLE
[BUG] gpc-replacer not replacing inside tags

### ISSUE THREAD

**Issue by MatAdam03** [gherking/gpc-replacer#2]
## Summary
Gpc-replacer doesn't replace inside tag names.

## Steps to Reproduce
Have this tag @loop(${iterationB})
Use this config 
{
      "path": "gpc-replacer",
      "configuration": {
        "iterationB": 5
      }
 }
### Expected behavior**
Expected tag after replacing @loop(5).

### Actual behavior**
Actual result after replace @loop(${iterationB})

**Comment by szikszail** [comment]
@MatAdam03 fixed with `gpc-replacer@1.0.1`
